# This is our base template - it won't be shown to users
name: &name Issue Template  # Using an anchor for the name
description: &description Create a new issue  # Using an anchor for the description

# Define the common body elements that will be shared
body: &baseBody  # This anchor will contain all shared fields
  - type: markdown
    attributes: &welcomeMessage
      value: |
        Thanks for taking the time to fill out this issue!

  - type: textarea
    id: summary
    attributes: &summaryField
      label: Summary
      description: A Summary of the issue
    validations: &requiredField
      required: true

  - type: textarea
    id: description
    attributes: &descriptionField
      label: Description
      description: A Description of the issue
    validations: *requiredField  # Reusing the required validation

  - type: dropdown
    id: version
    attributes: &versionField
      label: Version
      description: What version is this occurring in?
      options: &versionOptions
        - dev
        - 5.1
        - 5.0
        - 4.2
        - 4.1
        - 4.0
        - 3.2
        - 3.1
        - 3.0
        - 2.2
        - 2.1
        - 2.0

  - type: input
    id: keywords
    attributes: &keywordsField
      label: Keywords
      description: Keywords to help categorize the issue

  - type: checkboxes
    id: has-patch
    attributes: &patchField
      label: Has Patch
      options:
        - label: Has Patch
          required: false

  - type: checkboxes
    id: ui-ux
    attributes: &uiField
      label: UI/UX
      options:
        - label: UI/UX
          required: false

  - type: dropdown
    id: component
    attributes: &componentField
      label: Component
      description: Which component is affected?
      options: &componentOptions
        - contrib.admin
        - contrib.admindocs
        - contrib.auth
        - contrib.contenttypes
        - contrib.flatpages
        - contrib.humanize
        - contrib.messages
        - contrib.postgres
        - contrib.redirects
        - contrib.sessions
        - contrib.sitemaps
        - contrib.sites
        - contrib.staticfiles
        - contrib.syndication
        - Core (Cache system)
        - Core (Mail)
        - Core (Management commands)
        - Core (Other)
        - Core (Serialization)
        - Core (System checks)
        - Core (URLs)
        - CSRF
        - Database layer (models, ORM)
        - Documentation
        - Error reporting
        - File uploads/storage
        - Forms
        - Generic views
        - GIS
        - HTTP handling
        - Internationalization
        - Migrations
        - Packaging
        - Template system
        - Testing framework
        - Uncategorized (default selected)
        - Utilities
    validations: *requiredField

  - type: dropdown
    id: severity
    attributes: &severityField
      label: Severity
      description: How severe is this issue?
      options: &severityOptions
        - Normal
        - Release Blocker
    validations: *requiredField

  - type: checkboxes
    id: easy-pickings
    attributes: &easyField
      label: Easy Pickings
      options:
        - label: Easy Pickings
          required: false
