name: Bug Report
description: Report a bug (similar to Trac defect tickets)
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of this issue
      options:
        - new
        - assigned
        - reopened
        - closed
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Database
        - Documentation
        - Forms
        - ORM
        - Templates
        - URLs/HTTP
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - blocker
        - critical
        - major
        - minor
        - trivial
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: "Describe the bug here..."
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
    validations:
      required: true
