name: Feature Request
description: Suggest an enhancement (similar to Trac enhancement tickets)
body:
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of this feature request
      options:
        - new
        - accepted
        - needs-discussion
        - rejected
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - high
        - medium
        - low
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: "Describe your proposed feature here..."
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem would this feature solve?
      placeholder: "Explain the use case..."
    validations:
      required: true