name: Issue Type Setter
on:
  issues:
    types: [opened]

jobs:
  set-type:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            async function setIssueType() {
              const issue = context.payload.issue;
              const body = issue.body;
              
              // Extract the Type field value
              const typeMatch = body.match(/### Type\s*\n\n(.+?)(?:\n\n|$)/s);
              if (!typeMatch) return;
              
              const type = typeMatch[1].trim();
              let issueType = 'ISSUE';  // Default to regular issue
              
              // Only set to bug if explicitly selected
              if (type === 'Bug') {
                issueType = 'BUG';
              }
              
              // GraphQL mutation to update issue type
              const mutation = `
                mutation($issueId: ID!, $type: IssueType!) {
                  updateIssue(
                    input: {
                      id: "${issue.node_id}",
                      issueType: $type
                    }
                  ) {
                    issue {
                      id
                      issueType
                    }
                  }
                }
              `;
              
              try {
                await github.graphql(mutation, {
                  issueId: issue.node_id,
                  type: issueType
                });
                
                console.log(`Successfully set issue type to ${issueType}`);
              } catch (error) {
                console.error('Error setting issue type:', error);
              }
            }
            
            await setIssueType();